-- Creating tables for MENTAL_HEALTH_FINAL_PROJECT

CREATE TABLE EMPLOYEES (
     ID int NOT NULL,
     AGE int,
	 GENDER varchar(10),
	 COUNTRY_WORKING_IN varchar(20),
	 WFH varchar(20),
     PRIMARY KEY (ID)
);

CREATE TABLE MENTAL_HEALTH (
	ID int NOT NULL,
	MENTAL_HEALTH_COVERAGE varchar(10), 
	TECH_COMPANY int, 
	MENTAL_HEALTH_OPTIONS_UNDER_COVERAGE varchar,
	EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES varchar,
	MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT int, 
	PREV_EMPLOYERS_PROVIDE_MENTAL_HEALTH_BENEFITS varchar,
	AWARENESS_OF_MENTAL_HEALTH_COVERAGE_BY_PREV_EMPLOYERS varchar,
	PREV_EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES varchar,
	MENTAL_HEALTH_IDENTITY_HURT_YOUR_CAREER varchar,
	CURRENT_MENTAL_HEALTH_DISORDER varchar,
	FOREIGN KEY (ID) REFERENCES EMPLOYEES (ID),
	PRIMARY KEY (ID)
);